version: "3"

services:
  api1:
    image: fernandosvrosa/rinha:338bd3b11d55d9db1658b6bfeffe0429a8cf506a
    container_name: rinha1
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=scylla-node1:9042
      - NAME=rinha1
    depends_on:
      - scylla-node1
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rinha1.rule=Host(`localhost`)"
        - "traefik.http.services.rinha1.loadbalancer.server.port=3000"
    networks:
      scylla-net:

  api2:
    image: fernandosvrosa/rinha:338bd3b11d55d9db1658b6bfeffe0429a8cf506a
    container_name: rinha2
    restart: always
    ports:
      - "3001:3000"
    environment:
      - DB_HOST=scylla-node1:9042
      - NAME=rinha2
    depends_on:
      - scylla-node1
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rinha2.rule=Host(`localhost`)"
        - "traefik.http.services.rinha2.loadbalancer.server.port=3001"
    networks:
      scylla-net:

  traefik:
    image: traefik:v2.2
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9999"
      - "--providers.file.directory=/etc/traefik/dynamic"
    ports:
      - "9999:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      scylla-net:


  scylla-node1:
    image: scylladb/scylla
    restart: always
    container_name: scylla-node1
    ports:
      - "9042:9042" # CQL native transport
      - "10000:10000" # Prometheus metrics
      - "9180:9180" # Internode HTTP communication
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 150M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      scylla-net:

  scylla-node2:
    image: scylladb/scylla
    restart: always
    container_name: scylla-node2
    ports:
      - "9043:9042" # CQL native transport
      - "10001:10000" # Prometheus metrics
      - "9181:9180" # Internode HTTP communication
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 150M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      scylla-net:

networks:
    scylla-net:
        driver: bridge