version: "3"

services:
  api:
    image: fernandosvrosa/rinha:012d7a37e59866b98b0d04336512ed9350a2076e
    container_name: rinha
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=scylla-net:9042
    depends_on:
      - scylla-node1
    networks:
      scylla-net:

  scylla-node1:
    image: scylladb/scylla
    restart: always
    container_name: scylla-node1
    ports:
      - "9042:9042" # CQL native transport
      - "10000:10000" # Prometheus metrics
      - "9180:9180" # Internode HTTP communication
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 150M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      scylla-net:

  scylla-node2:
    image: scylladb/scylla
    restart: always
    container_name: scylla-node2
    ports:
      - "9043:9042" # CQL native transport
      - "10001:10000" # Prometheus metrics
      - "9181:9180" # Internode HTTP communication
    command: --seeds=scylla-node1,scylla-node2 --smp 1 --memory 150M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      scylla-net:

networks:
    scylla-net:
        driver: bridge