version: "3"

services:
  api1:
    image: fernandosvrosa/rinha:828e6f3be36101735abdf29604571e6eb14f46a1
    container_name: rinha1
    restart: always
    environment:
      - DB_HOST=scylla-node1:9042
      - CONN_MAX=20
    depends_on:
      - scylla-node1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rinha.rule=Host(`localhost`)"
      - "traefik.http.services.rinha.loadbalancer.server.port=3000"
    networks:
      scylla-net:
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "130MB"

  api2:
    image: fernandosvrosa/rinha:828e6f3be36101735abdf29604571e6eb14f46a1
    container_name: rinha2
    restart: always
    environment:
      - DB_HOST=scylla-node1:9042
      - CONN_MAX=20
    depends_on:
      - scylla-node1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rinha.rule=Host(`localhost`)"
      - "traefik.http.services.rinha.loadbalancer.server.port=3000"
    networks:
      scylla-net:
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "130MB"

  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:9999"
      - "--providers.file.directory=/etc/traefik/dynamic"
    ports:
      - "9999:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      scylla-net:
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "90MB"


  scylla-node1:
    image: scylladb/scylla
    restart: always
    container_name: scylla-node1
    ports:
      - "9042:9042" # CQL native transport
      - "10000:10000" # Prometheus metrics
      - "9180:9180" # Internode HTTP communication
    command: --seeds=scylla-node1 --smp 1 --memory 200M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      scylla-net:
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"


networks:
    scylla-net:
        driver: bridge